package youzhao.kuaifang.mockdata;

public class MockFirstPage extends Mock {

	private String mockFirstPage = "  {"
			+"    \"GX\": \"\","
			+"    \"CS\": \"\","
			+"    \"KF\": {"
			+"        \"TL\": \"24小时客服电话\","
			+"        \"PY\": \"4008-699-591\","
			+"        \"YYMC\": \"药师咨询专线\","
			+"        \"YYTEL\": \"01080697909\","
			+"        \"XXTS\": \"1小时免费送药上门，0.1元起送\","
			+"        \"PYO\": \"\","
			+"        \"GN\": \"\","
			+"        \"CJ\": 3,"
			+"        \"GJZ\": ["
			+"            {"
			+"                \"KN\": \"感冒\","
			+"                \"PC\": \"http://p2.kfyao.com/kn/kn2016102915021241457.png\""
			+"            },"
			+"            {"
			+"                \"KN\": \"消炎\","
			+"                \"PC\": \"http://p2.kfyao.com/kn/kn2016112117025648642.png\""
			+"            },"
			+"            {"
			+"                \"KN\": \"咳嗽\","
			+"                \"PC\": \"http://p2.kfyao.com/kn/kn2016112117022169427.png\""
			+"            },"
			+"            {"
			+"                \"KN\": \"妇科\","
			+"                \"PC\": \"http://p2.kfyao.com/kn/kn2016110116523438112.png\""
			+"            },"
			+"            {"
			+"                \"KN\": \"清热解毒\","
			+"                \"PC\": \"http://p2.kfyao.com/kn/kn2016102914585192397.png\""
			+"            },"
			+"            {"
			+"                \"KN\": \"维生素\","
			+"                \"PC\": \"http://p2.kfyao.com/kn/kn2016102914564130246.png\""
			+"            },"
			+"            {"
			+"                \"KN\": \"滴眼液\","
			+"                \"PC\": \"http://p2.kfyao.com/kn/kn2016102914582675589.png\""
			+"            },"
			+"            {"
			+"                \"KN\": \"口罩\","
			+"                \"PC\": \"http://p2.kfyao.com/kn/kn2016110708530147442.png\""
			+"            },"
			+"            {"
			+"                \"KN\": \"脚气\","
			+"                \"PC\": \"http://p2.kfyao.com/kn/kn2016102914532080534.png\""
			+"            },"
			+"            {"
			+"                \"KN\": \"膏药\","
			+"                \"PC\": \"http://p2.kfyao.com/kn/kn2016102914561988648.png\""
			+"            },"
			+"            {"
			+"                \"KN\": \"胃炎\","
			+"                \"PC\": \"http://p2.kfyao.com/kn/kn2016102914563141334.png\""
			+"            }"
			+"        ]"
			+"    },"
			+"    \"SY\": {"
			+"        \"ID\": 0,"
			+"        \"TL\": 0,"
			+"        \"PY\": 0,"
			+"        \"ADTJ\": \"http://okm.kfyao.com/v3/images/ad/tj1009.jpg\","
			+"        \"ADPP\": \"http://okm.kfyao.com/v3/images/ad/ppad4.jpg\","
			+"        \"ADYY\": \"\","
			+"        \"ADZY\": \"\","
			+"        \"ADTJ2\": \"http://okm.kfyao.com/v3/images/ad/tj1009.jpg\","
			+"        \"ADPP2\": \"http://okm.kfyao.com/v3/images/ad/ppad4.jpg\","
			+"        \"ADYY2\": \"\","
			+"        \"ADZY2\": \"\","
			+"        \"GN\": null,"
			+"        \"CJ\": \"\","
			+"        \"MNO\": \"\","
			+"        \"NT\": \"\""
			+"    },"
			+"    \"WZ\": {"
			+"        \"TL\": \"购物车\","
			+"        \"PY\": \"购物\","
			+"        \"PYO\": \"订单\","
			+"        \"CF\": \"药师咨询\","
			+"        \"CJ\": \"<center><font color='#A4A4A4'>互联网药品交易服务资格证书：京C2016002</font></center>\""
			+"    },"
			+"    \"MU\": \"\","
			+"    \"SYSJ\": ["
			+"        {"
			+"            \"ID\": 1,"
			+"            \"MM\": {"
			+"                \"TJ\": {"
			+"                    \"BARPC\": \"http://okm.kfyao.com/v3/images/tj/tj02.jpg\","
			+"                    \"BARPC2\": \"http://okm.kfyao.com/v3/images/tj/top3.jpg\","
			+"                    \"BARURL\": \"http://okm.kfyao.com/v3/tj.php?tl=特价活动\","
			+"                    \"TJMM\": ["
			+"                        {"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/images/tj/2864.jpg\","
			+"                            \"PID\": 2864"
			+"                        },"
			+"                        {"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/images/tj/13365_3.jpg\","
			+"                            \"PID\": 13365"
			+"                        },"
			+"                        {"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/images/tj/7538_3.jpg\","
			+"                            \"PID\": 7538"
			+"                        },"
			+"                        {"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/images/tj/1961_3.jpg\","
			+"                            \"PID\": 1961"
			+"                        }"
			+"                    ],"
			+"                    \"TOPAD\": ["
			+"                        {"
			+"                            \"ID\": 0,"
			+"                            \"WID\": 0,"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/tj.php?tl=特价活动\","
			+"                            \"PC\": \"http://okm.kfyao.com/v3/images/ad/toptj.jpg\""
			+"                        },"
			+"                        {"
			+"                            \"WID\": 24,"
			+"                            \"ID\": 0,"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/ztl.php?ty=24&tl=家庭常备 \","
			+"                            \"PC\": \"http://okm.kfyao.com/v3/images/ad/top24-4.jpg\""
			+"                        },"
			+"                        {"
			+"                            \"WID\": 26,"
			+"                            \"ID\": 0,"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/ztl.php?ty=26&tl=瘦身专题\","
			+"                            \"PC\": \"http://okm.kfyao.com/v3/images/ad/top26-3.jpg\""
			+"                        }"
			+"                    ]"
			+"                },"
			+"                \"ZT\": {"
			+"                    \"TL\": \"主题特卖\","
			+"                    \"MM\": ["
			+"                        {"
			+"                            \"PC\": \"http://p1.kfyao.com/44/63/4463170406174614827_1080_460_.jpg\","
			+"                            \"ZID\": \"32\","
			+"                            \"URL\": \"http://okm.kfyao.com/v3/ztl.php?tl=抗过敏\""
			+"                        },"
			+"                        {"
			+"                            \"PC\": \"http://p1.kfyao.com/18/38/1838170401104719578_1080_460_.jpg\","
			+"                            \"ZID\": \"31\","
			+"                            \"URL\": \"http://okm.kfyao.com/v3/ztl.php?tl=出游行\""
			+"                        },"
			+"                        {"
			+"                            \"PC\": \"http://p1.kfyao.com/79/53/7953170406174802279_1080_460_.jpg\","
			+"                            \"ZID\": \"26\","
			+"                            \"URL\": \"http://okm.kfyao.com/v3/ztl.php?tl=瘦身专题\""
			+"                        }"
			+"                    ],"
			+"                    \"URL\": \"http://okm.kfyao.com/v3/zt.php?tl=主题特卖\""
			+"                },"
			+"                \"PP\": {"
			+"                    \"TL\": \"品牌推荐\","
			+"                    \"MM\": ["
			+"                        {"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/ppl.php?tl=同仁堂\","
			+"                            \"PC\": \"http://okm.kfyao.com/v3/images/pp/1.png\","
			+"                            \"ZID\": \"1\","
			+"                            \"TL\": \"同仁堂\""
			+"                        },"
			+"                        {"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/ppl.php?tl=云南白药\","
			+"                            \"PC\": \"http://okm.kfyao.com/v3/images/pp/2.png\","
			+"                            \"ZID\": \"2\","
			+"                            \"TL\": \"云南白药\""
			+"                        },"
			+"                        {"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/ppl.php?tl=桂龙药业\","
			+"                            \"PC\": \"http://okm.kfyao.com/v3/images/pp/9.png\","
			+"                            \"ZID\": \"9\","
			+"                            \"TL\": \"桂龙药业\""
			+"                        },"
			+"                        {"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/ppl.php?tl=扬子江\","
			+"                            \"PC\": \"http://okm.kfyao.com/v3/images/pp/10.png\","
			+"                            \"ZID\": \"10\","
			+"                            \"TL\": \"扬子江\""
			+"                        },"
			+"                        {"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/ppl.php?tl=白云山\","
			+"                            \"PC\": \"http://okm.kfyao.com/v3/images/pp/4.png\","
			+"                            \"ZID\": \"4\","
			+"                            \"TL\": \"白云山\""
			+"                        },"
			+"                        {"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/ppl.php?tl=华润三九\","
			+"                            \"PC\": \"http://okm.kfyao.com/v3/images/pp/3.png\","
			+"                            \"ZID\": \"3\","
			+"                            \"TL\": \"华润三九\""
			+"                        },"
			+"                        {"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/ppl.php?tl=杜蕾斯\","
			+"                            \"PC\": \"http://okm.kfyao.com/v3/images/pp/5.png\","
			+"                            \"ZID\": \"5\","
			+"                            \"TL\": \"杜蕾斯\""
			+"                        },"
			+"                        {"
			+"                            \"URL\": \"http://okm.kfyao.com/v3/ppl.php?tl=九芝堂\","
			+"                            \"PC\": \"http://okm.kfyao.com/v3/images/pp/6.png\","
			+"                            \"ZID\": \"6\","
			+"                            \"TL\": \"九芝堂\""
			+"                        }"
			+"                    ],"
			+"                    \"URL\": \"http://okm.kfyao.com/v3/pp.php?tl=品牌推荐\""
			+"                },"
			+"                \"JJTJ\": {"
			+"                    \"TL\": \"当季热销商品\","
			+"                    \"PC\": \"http://okm.kfyao.com/v3/images/jj/jjbj.png\","
			+"                    \"MM\": ["
			+"                        {"
			+"                            \"PID\": 4939,"
			+"                            \"TL\": \"[康恩贝] 肠炎宁片\","
			+"                            \"PC\": \"http://p1.kfyao.com/61/48/6148160423154332426.jpg\","
			+"                            \"MS\": \"0.42gx12片x4板\","
			+"                            \"MM\": \"清热利湿，行气。用于湿热蕴结胃肠所致的腹泻，小儿消化不良。\","
			+"                            \"PR\": \"22.60\""
			+"                        },"
			+"                        {"
			+"                            \"PID\": 3782,"
			+"                            \"TL\": \"[999] 咽炎片\","
			+"                            \"PC\": \"http://p1.kfyao.com/20/54/2054170113100719222.jpg\","
			+"                            \"MS\": \"0.25gx12片x4板（换包装啦，新老包装随机发）\","
			+"                            \"MM\": \"养阴润肺，清热解毒，清利咽喉，镇咳止痒。用于慢性咽炎引起咽干，咽痒，刺激性咳嗽。\","
			+"                            \"PR\": \"9.60\""
			+"                        },"
			+"                        {"
			+"                            \"PID\": 469,"
			+"                            \"TL\": \"[感康] 感康\","
			+"                            \"PC\": \"http://p1.kfyao.com/48/22/4822161020174442423.jpg\","
			+"                            \"MS\": \"12片（换包装啦，新老包装随机发）\","
			+"                            \"MM\": \"适用于缓解普通感冒及流行性感冒引起的发热、头痛、四肢酸痛、打喷嚏、流鼻涕、鼻塞、咽痛等症状。\","
			+"                            \"PR\": \"13.00\""
			+"                        },"
			+"                        {"
			+"                            \"PID\": 12361,"
			+"                            \"TL\": \"[标婷] 标婷维生素E乳\","
			+"                            \"PC\": \"http://p1.kfyao.com/71/59/7159161025105344337.jpg\","
			+"                            \"MS\": \"100g（喷头式）（新老包装交替中随机发货）\","
			+"                            \"MM\": \"用于皮肤干燥并有润肤、保湿作用。\","
			+"                            \"PR\": \"9.60\""
			+"                        },"
			+"                        {"
			+"                            \"PID\": 3560,"
			+"                            \"TL\": \"[扬子江] 蓝芩口服液\","
			+"                            \"PC\": \"http://p1.kfyao.com/43/95/4395161216110546444.jpg\","
			+"                            \"MS\": \"10mlX6支\","
			+"                            \"MM\": \"清热解毒，利咽消肿。用于急性咽炎、肺胃实热证所致的咽痛、咽干、咽部灼热。\","
			+"                            \"PR\": \"18.00\""
			+"                        },"
			+"                        {"
			+"                            \"PID\": 276,"
			+"                            \"TL\": \"[葵花药业] 小儿肺热咳喘口服液\","
			+"                            \"PC\": \"http://p1.kfyao.com/87/30/8730160414154247818.jpg\","
			+"                            \"MS\": \"10ml×6支\","
			+"                            \"MM\": \"清热解毒，宣肺化痰。用于热邪犯于肺卫所致发热、汗出、微恶风寒、咳嗽、痰黄，或兼喘息、口干而渴。\","
			+"                            \"PR\": \"29.80\""
			+"                        },"
			+"                        {"
			+"                            \"PID\": 3217,"
			+"                            \"TL\": \"[云南白药] 蒲地蓝消炎片\","
			+"                            \"PC\": \"http://p1.kfyao.com/12/89/1289160424144959512.jpg\","
			+"                            \"MS\": \"0.3克x24片x2板  薄膜衣片\","
			+"                            \"MM\": \"清热解毒，抗炎消肿。用于疖肿、咽炎、扁桃腺炎。\","
			+"                            \"PR\": \"15.00\""
			+"                        },"
			+"                        {"
			+"                            \"PID\": 3790,"
			+"                            \"TL\": \"[香港京都] 京都念慈菴蜜炼川贝枇杷膏\","
			+"                            \"PC\": \"http://p1.kfyao.com/82/76/8276140905143541379.jpg\","
			+"                            \"MS\": \"150ml\","
			+"                            \"MM\": \"润肺化痰、止咳平喘、护喉利咽、生津补气、调心降火。本品适用于伤风咳嗽、痰稠、痰多气喘、咽喉干痒及声音嘶哑。\","
			+"                            \"PR\": \"25.60\""
			+"                        },"
			+"                        {"
			+"                            \"PID\": 337,"
			+"                            \"TL\": \"[江中] 健胃消食片\","
			+"                            \"PC\": \"http://p1.kfyao.com/40/27/4027160414152245227.jpg\","
			+"                            \"MS\": \"0.8gx8片x4板  成人\","
			+"                            \"MM\": \"健胃消食。用于脾胃虚弱所致的食积，症见不思饮食、嗳腐酸臭、脘腹胀满；消化不良见上述证候者。\","
			+"                            \"PR\": \"7.20\""
			+"                        },"
			+"                        {"
			+"                            \"PID\": 6032,"
			+"                            \"TL\": \"[日本冈本] 冈本避孕套\","
			+"                            \"PC\": \"http://p1.kfyao.com/50/69/5069160831125209765.jpg\","
			+"                            \"MS\": \"3只/盒  超润滑\","
			+"                            \"MM\": \"超润滑冈本避孕套\","
			+"                            \"PR\": \"11.50\""
			+"                        }"
			+"                    ]"
			+"                }"
			+"            }"
			+"        }"
			+"    ]"
			+"}";


	public String getData() {
		// TODO Auto-generated method stub
		return mockFirstPage;
	}

}
